### ISSUE TITLE
ball get through the racket if velocity is too high

### ISSUE THREAD

**Issue by favu100** [Andriocity/ModernPong#4]

**Comment by MaFeg100** [comment]
The solution is to set the position of the ball who hits the bounds to: 
- left wall -> position.x = radius; 
- right wall -> position.x = Screen_W - radius; 
- upper wall -> position.y = radius;
- lower wall -> position.y = Screen_H - radius; 

** You  can also use my math call to cut of the lower bits of the values to prevent  calculation mistakes.

**Comment by MaFeg100** [comment]
But the Idea above should work, because it always sets the positon to smooth values.

**Comment by favu100** [comment]
This bug is fixed now. I forgot to check the bottom wall :D

**Comment by favu100** [comment]
Fixed

**Comment by favu100** [comment]
bug returns after gdx update

**Comment by favu100** [comment]
fixed
