### ISSUE TITLE
two balls can stick together after the collision

### ISSUE THREAD

**Issue by favu100** [Andriocity/ModernPong#5]

**Comment by MaFeg100** [comment]
This bug can be fixed if each of the colliding balls do one move operation so that they move directly if they hit each other. If they don't you must wait until every possible collision is checked. In this time the balls keep their old direction.

**Comment by favu100** [comment]
Fixed

**Comment by favu100** [comment]
bug returns after gdx update

**Comment by favu100** [comment]
fixed
